"use strict";
exports.__esModule = true;
var inversify_1 = require("inversify");
var types_1 = require("./types");
var Crawler_1 = require("../services/Crawler");
var AxiosMarkupFetcher_1 = require("../services/AxiosMarkupFetcher");
var CheerioTraverser_1 = require("../services/CheerioTraverser");
var WebsiteRepository_1 = require("../repositories/WebsiteRepository");
var MongoClient_1 = require("../clients/MongoClient");
var ExitHandler_1 = require("../services/ExitHandler");
var Logger_1 = require("../services/Logger");
var LocalJSONStorageClient_1 = require("../clients/LocalJSONStorageClient");
var QueueRepository_1 = require("../repositories/QueueRepository");
var UrlQueue_1 = require("../services/UrlQueue");
var container = new inversify_1.Container();
container.bind(types_1.TYPES.WebCrawler).to(Crawler_1.Crawler).inSingletonScope();
container.bind(types_1.TYPES.MarkupFetcher).to(AxiosMarkupFetcher_1.AxiosMarkupFetcher);
container.bind(types_1.TYPES.WebsiteRepository).to(WebsiteRepository_1.WebsiteRepository);
container.bind(types_1.TYPES.QueueRepositoryInterface).to(QueueRepository_1.QueueRepository).inSingletonScope();
container.bind(types_1.TYPES.MarkupTraverser).to(CheerioTraverser_1.CheerioTraverser);
container.bind(types_1.TYPES.DBClient).to(MongoClient_1.MongoClient).inSingletonScope();
container.bind(types_1.TYPES.ExitHandlerInterface).to(ExitHandler_1.ExitHandler);
container.bind(types_1.TYPES.LoggerInterface).to(Logger_1.Logger).inSingletonScope();
container.bind(types_1.TYPES.PersistenceClient).to(LocalJSONStorageClient_1.LocalJSONStorageClient).inSingletonScope();
container.bind(types_1.TYPES.UrlQueueInterface).to(UrlQueue_1.UrlQueue).inSingletonScope();
exports["default"] = container;
